# Generated by Django 3.1.6 on 2021-02-03 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 12, 40, 54, 203349, tzinfo=utc)),
        ),
    ]
